apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bussie-web-cert
  namespace: bussie-web-ns
spec:
  dnsNames:
    - doemijmaareenbussiewaareenautoachteropkan.nl
  secretName: bussie-web-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer