apiVersion: apps/v1
kind: Deployment
metadata:
  name: bussie-web
  namespace: bussie-web-ns
  labels:
    app: bussie-web
spec:
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 0
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: bussie-web
  template:
    metadata:
      labels:
        app: bussie-web
    spec:
      containers:
      - name: bussie-web
        image: kaijehenstra/bussie
        imagePullPolicy: Always
        resources:
          limits:
            memory: 350Mi
            cpu: "0.25"
          requests:
            memory: 10Mi
            cpu: 1m
        ports:
        - containerPort: 80