apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bussie-web-ingress
  namespace: bussie-web-ns
spec:
  tls:
  - hosts:
    - doemijmaareenbussiewaareenautoachteropkan.nl
    secretName: bussie-web-tls
  rules:
  - host: doemijmaareenbussiewaareenautoachteropkan.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bussie-web-service
            port:
              number: 80
